config/routes.rb
Chatly::Application.routes.draw do
 
  root to: 'chats#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :chats
  resources :users
  resources :sessions
  resources :messages

end

app/models/chat.rb
class Chat < ActiveRecord::Base

  has_many :memberships
  has_many :users, through: :memberships

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  belongs_to :user
  belongs_to :chat

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :body

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :memberships
  has_many :chats, through: :memberships
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :authorize

  def index
    @chats = current_user.chats
  end

  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new()
    if @chat.save
      chat_params[:user_ids].each do |id|
        Membership.create(user_id: id, chat_id: @chat.id)
      end
      redirect_to chat_path(@chat)
    else
      render 'new'
    end
  end

  def show
    @chat = Chat.find(params[:id])
    @messages = Message.where(chat_id: params[:id])
    @message = Message.new(chat_id: params[:id])
  end

private

  def chat_params
    params.require(:chat).permit(:user_ids => [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    if @message.save
      redirect_to chat_path(@message.chat_id)
    else
    end
  end

private

  def message_params
    params.require(:message).permit(:body, :chat_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

private
  
  def users_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/index.html.erb
<h1>All of your chats!</h1>
<%= link_to "Create a new chat", new_chat_path %>
<ul>
  <% current_user.chats.each do |c| %>
    <div>
      <h2>Chat</h2>
      <p><%= c.created_at %></p>
      <p>Members: <%= Membership.where(chat_id: c).count %></p>
      <%= link_to "Go to chat", chat_path(c) %>
    </div>
  <% end %>
</ul>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= simple_form_for @chat do |f| %>
  Who do you want to invite?
  <%= f.association :users, label: false, as: :check_boxes %>
  <br>
  <%= f.submit %>
<% end %>

app/views/chats/show.html.erb
<div class="row">
  <h1>This is a chat!</h1>
  <%= link_to "See all chats", chats_path %>
  <ul class="list-inline">
    <% @chat.users.each do |u| %>
      <li><span class="label label-default"><%= u.name %></span></li>
    <% end %>
  </ul>

  <ul class="list-group">
    <% @messages.each do |m| %>
      <li class="list-group-item"><span class="label label-primary"><%= m.user.name %></span> <%= m.body %></li>
    <% end %>
  </ul>
</div>
<div class="row">
  <div class="col-sm-4">
  <%= simple_form_for @message do |f| %>
    <%= f.input :body %>
    <%= f.input :chat_id, as: :hidden %>
    <br>
    <%= f.submit "Post a new message.", class: "btn btn-primary" %>
  <% end %>
  </div>
  <div class="col-sm-2">
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log Out", logout_path %>
  <% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
  <% end %>

  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end %>

  <%= yield %>

</div>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>